---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:17.2.1
  amd64: ghcr.io/hassio-addons/base/amd64:17.2.1
  armhf: ghcr.io/hassio-addons/base/armhf:17.2.1
  armv7: ghcr.io/hassio-addons/base/armv7:17.2.1
  i386: ghcr.io/hassio-addons/base/i386:17.2.1
# identity: hans@expaso.nl
# base_identity: codenotary@frenck.dev
codenotary:
  base_image: codenotary@frenck.dev
  signer: hans@expaso.nl
